//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDataAcessLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProdDescription { get; set; }
        public Nullable<int> Price { get; set; }
        public string categoryId { get; set; }
    
        public virtual tbl_Category1 tbl_Category1 { get; set; }
    }
}
